spring.application.name=Fhram

spring.datasource.url=jdbc:oracle:thin:@project-db-campus.smhrd.com:1523:XE
spring.datasource.username=cd_26K_HI1_p2_5
spring.datasource.password=smhrd5
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

server.port=8089