-- ALERT 테이블 확장: 수량 불일치(반출 기반) 알림 + 재고 부족(카메라 기반) 알림을 한 테이블에 담는다.
-- 실행 전 ALERT 데이터가 0건인 것을 확인함 (NOT NULL 컬럼 추가 가능)
--
-- ALERT_TYPE     : MISMATCH(전표·세그먼트 수량 불일치) / LOW_STOCK(재고 부족)
-- OUTBOUND_ID    : MISMATCH 알림만 값이 있고, LOW_STOCK 은 반출과 무관하므로 NULL 허용으로 변경
-- MEDICINE_ID    : 모든 알림이 가진다. 관리자(병원) 구분은 MEDICINE -> CAMERA -> ADMIN 으로 한다.
-- ALERT_TIME     : 알림 발생 시각
-- PROCESS_STATUS : PENDING(미처리) / DONE(관리자가 확인 처리)

ALTER TABLE ALERT MODIFY (OUTBOUND_ID NULL);

ALTER TABLE ALERT ADD (
    ALERT_TYPE   VARCHAR2(20) NOT NULL,
    MEDICINE_ID  NUMBER(19)   NOT NULL,
    ALERT_TIME   DATE         NOT NULL
);

ALTER TABLE ALERT MODIFY (PROCESS_STATUS DEFAULT 'PENDING' NOT NULL);

ALTER TABLE ALERT ADD CONSTRAINT CK_ALERT_TYPE CHECK (ALERT_TYPE IN ('MISMATCH', 'LOW_STOCK'));
ALTER TABLE ALERT ADD CONSTRAINT CK_ALERT_STATUS CHECK (PROCESS_STATUS IN ('PENDING', 'DONE'));
ALTER TABLE ALERT ADD CONSTRAINT FK_ALERT_MEDICINE FOREIGN KEY (MEDICINE_ID) REFERENCES MEDICINE (MEDICINE_ID);
