-- ID 채번 동시성 문제 해결
-- 지금까지 CAMERA/MEDICINE/HOSPITAL_STAFF/SUBSCRIPTION/WARD는 자바에서
-- "SELECT MAX(id)+1" 로 직접 다음 번호를 계산해서 넣었는데, 두 요청이 동시에 들어오면
-- 같은 번호를 계산해서 하나가 PK 충돌로 실패할 수 있었다.
-- Oracle SEQUENCE는 NEXTVAL 호출이 원자적이라 이 문제가 없다.
-- (IDENTITY 컬럼은 캠퍼스 DB 버전이 지원 안 해서 못 쓰지만 SEQUENCE는 8i 때부터 있는 기본 기능이라 문제없음)
-- 실행 전 현재 최대값 확인: CAMERA=5, MEDICINE=6, HOSPITAL_STAFF=2, SUBSCRIPTION=3, WARD=5

CREATE SEQUENCE CAMERA_SEQ START WITH 6 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MEDICINE_SEQ START WITH 7 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HOSPITAL_STAFF_SEQ START WITH 3 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SUBSCRIPTION_SEQ START WITH 4 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE WARD_SEQ START WITH 6 INCREMENT BY 1 NOCACHE;
