-- 시연 영상용 전체 데이터 초기화 (2026-09-23) - 회원가입부터 새로 넣기 위해 모든 테이블을 비운다
-- 복구가 필요하면 sql/backup_20260923.sql 실행
-- 삭제 순서 = FK 역순 (자식 테이블 먼저)

DELETE FROM ALERT;
DELETE FROM OUTBOUND;
DELETE FROM SLIP_ITEM;
DELETE FROM SLIP;
DELETE FROM WARD;
DELETE FROM MEDICINE;
DELETE FROM CAMERA;
DELETE FROM HOSPITAL_STAFF;
DELETE FROM SUBSCRIPTION;
DELETE FROM MEMBER;
COMMIT;

-- ID 시퀀스 1부터 재시작 (캠퍼스 DB 버전이 ALTER SEQUENCE ... RESTART를 지원 안 해서 DROP 후 재생성)
DROP SEQUENCE CAMERA_SEQ;
CREATE SEQUENCE CAMERA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
DROP SEQUENCE MEDICINE_SEQ;
CREATE SEQUENCE MEDICINE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
DROP SEQUENCE HOSPITAL_STAFF_SEQ;
CREATE SEQUENCE HOSPITAL_STAFF_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
DROP SEQUENCE SUBSCRIPTION_SEQ;
CREATE SEQUENCE SUBSCRIPTION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
DROP SEQUENCE WARD_SEQ;
CREATE SEQUENCE WARD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
DROP SEQUENCE OUTBOUND_SEQ;
CREATE SEQUENCE OUTBOUND_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
DROP SEQUENCE ALERT_SEQ;
CREATE SEQUENCE ALERT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
