-- FramVision 전체 테이블 생성 스크립트
-- 실제 운영 DB(project-db-campus)의 현재 구조를 그대로 반영함 (2026-09-21 기준)
-- 생성 순서 = FK 의존 순서 (참조되는 테이블이 먼저 와야 함)

-- 1) 회원
CREATE TABLE MEMBER (
    MEMBER_ID     VARCHAR2(50)   NOT NULL,
    PASSWORD      VARCHAR2(100),
    EMAIL         VARCHAR2(100),
    PHONE         VARCHAR2(20),
    MEMBER_NAME   VARCHAR2(50),
    FONT_SIZE     NUMBER(10),
    SCREEN_THEME  VARCHAR2(20),
    CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_ID)
);

-- 2) 구독정보
CREATE TABLE SUBSCRIPTION (
    SUBSCRIPTION_ID  NUMBER(19)     NOT NULL,
    ADMIN_ID         VARCHAR2(50),
    PRODUCT_NAME     VARCHAR2(100)  NOT NULL,
    PAYMENT_METHOD   VARCHAR2(30),
    PAYMENT_STATUS   VARCHAR2(20)   NOT NULL,
    START_DATE       DATE           NOT NULL,
    END_DATE         DATE,
    CONSTRAINT PK_SUBSCRIPTION PRIMARY KEY (SUBSCRIPTION_ID),
    CONSTRAINT FK_SUBSCRIPTION_ADMIN FOREIGN KEY (ADMIN_ID) REFERENCES MEMBER (MEMBER_ID)
);

-- 3) 카메라
CREATE TABLE CAMERA (
    CAMERA_ID          NUMBER(19)     NOT NULL,
    CAMERA_NAME        VARCHAR2(100)  NOT NULL,
    CONNECTION_STATUS  VARCHAR2(20),
    ADMIN_ID           VARCHAR2(50)   NOT NULL,
    STREAM_URL         VARCHAR2(255),
    CONSTRAINT PK_CAMERA PRIMARY KEY (CAMERA_ID),
    CONSTRAINT FK_CAMERA_ADMIN FOREIGN KEY (ADMIN_ID) REFERENCES MEMBER (MEMBER_ID)
);

-- 4) 병원 병동 정보 (병동번호는 병원별로만 유일함 - PK는 별도 대체키)
CREATE TABLE WARD (
    WARD_SEQ_ID  NUMBER(10)    NOT NULL,
    WARD_CODE    VARCHAR2(100) NOT NULL,
    WARD_NAME    VARCHAR2(50)  NOT NULL,
    LOCATION     VARCHAR2(100),
    ADMIN_ID     VARCHAR2(50)  NOT NULL,
    CONSTRAINT PK_WARD PRIMARY KEY (WARD_SEQ_ID),
    CONSTRAINT UK_WARD_ADMIN_CODE UNIQUE (ADMIN_ID, WARD_CODE),
    CONSTRAINT FK_WARD_ADMIN FOREIGN KEY (ADMIN_ID) REFERENCES MEMBER (MEMBER_ID)
);

-- 5) 의약품
CREATE TABLE MEDICINE (
    MEDICINE_ID    NUMBER(19)      NOT NULL,
    MEDICINE_NAME  VARCHAR2(100)   NOT NULL,
    HIGH_RISK_YN   VARCHAR2(1)     NOT NULL,
    MANUFACTURER   VARCHAR2(100)   NOT NULL,
    REGISTER_DATE  DATE,
    REGION_HEIGHT  BINARY_DOUBLE,
    REGION_WIDTH   BINARY_DOUBLE,
    REGION_X       BINARY_DOUBLE,
    REGION_Y       BINARY_DOUBLE,
    CAMERA_ID      NUMBER(19),
    MIN_QTY        NUMBER(10),
    ADMIN_ID       VARCHAR2(50)    NOT NULL,
    CONSTRAINT PK_MEDICINE PRIMARY KEY (MEDICINE_ID),
    CONSTRAINT CK_MEDICINE_MIN_QTY CHECK (MIN_QTY IS NULL OR MIN_QTY >= 0),
    CONSTRAINT FK_MEDICINE_CAMERA FOREIGN KEY (CAMERA_ID) REFERENCES CAMERA (CAMERA_ID),
    CONSTRAINT FK_MEDICINE_ADMIN FOREIGN KEY (ADMIN_ID) REFERENCES MEMBER (MEMBER_ID)
);

-- 6) 병원 직원 정보
CREATE TABLE HOSPITAL_STAFF (
    HISTORY_ID  NUMBER(19)    NOT NULL,
    ADMIN_ID    VARCHAR2(50),
    STAFF_ID    VARCHAR2(50),
    CONSTRAINT PK_HOSPITAL_STAFF PRIMARY KEY (HISTORY_ID),
    CONSTRAINT FK_STAFF_ADMIN FOREIGN KEY (ADMIN_ID) REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT FK_STAFF_STAFF FOREIGN KEY (STAFF_ID) REFERENCES MEMBER (MEMBER_ID)
);

-- 7) 요구전표 기록 (헤더)
CREATE TABLE SLIP (
    SLIP_ID         VARCHAR2(100) NOT NULL,
    WARD_ID         NUMBER(10)    NOT NULL,
    REQUESTER_NAME  VARCHAR2(50)  NOT NULL,
    SLIP_DATE       DATE,
    CONSTRAINT PK_SLIP PRIMARY KEY (SLIP_ID),
    CONSTRAINT FK_SLIP_WARD FOREIGN KEY (WARD_ID) REFERENCES WARD (WARD_SEQ_ID)
);

-- 8) 전표 품목 (전표 1건에 의약품 여러 줄)
CREATE TABLE SLIP_ITEM (
    SLIP_ID      VARCHAR2(100) NOT NULL,
    ITEM_NO      NUMBER(3)     NOT NULL,
    MEDICINE_ID  NUMBER(19)    NOT NULL,
    REQUEST_QTY  NUMBER(10)    NOT NULL,
    CONSTRAINT PK_SLIP_ITEM PRIMARY KEY (SLIP_ID, ITEM_NO),
    CONSTRAINT UK_SLIP_ITEM_MEDICINE UNIQUE (SLIP_ID, MEDICINE_ID),
    CONSTRAINT FK_SLIP_ITEM_SLIP FOREIGN KEY (SLIP_ID) REFERENCES SLIP (SLIP_ID),
    CONSTRAINT FK_SLIP_ITEM_MEDICINE FOREIGN KEY (MEDICINE_ID) REFERENCES MEDICINE (MEDICINE_ID)
);

-- 9) 의약품 실제반출 정보
-- FK_OUTBOUND_SLIP_ITEM: "이 전표에 실제로 적힌 약만 출고 기록에 넣을 수 있다"를 DB가 보장
CREATE TABLE OUTBOUND (
    OUTBOUND_ID    NUMBER(10)    NOT NULL,
    SLIP_ID        VARCHAR2(100) NOT NULL,
    MEDICINE_ID    NUMBER(10)    NOT NULL,
    WARD_ID        NUMBER(10)    NOT NULL,
    OUTBOUND_QTY   NUMBER(10)    NOT NULL,
    OUTBOUND_TIME  DATE,
    ABNORMAL_YN    VARCHAR2(1),
    CONSTRAINT PK_OUTBOUND PRIMARY KEY (OUTBOUND_ID),
    CONSTRAINT FK_OUTBOUND_SLIP FOREIGN KEY (SLIP_ID) REFERENCES SLIP (SLIP_ID),
    CONSTRAINT FK_OUTBOUND_MEDICINE FOREIGN KEY (MEDICINE_ID) REFERENCES MEDICINE (MEDICINE_ID),
    CONSTRAINT FK_OUTBOUND_WARD FOREIGN KEY (WARD_ID) REFERENCES WARD (WARD_SEQ_ID),
    CONSTRAINT FK_OUTBOUND_SLIP_ITEM FOREIGN KEY (SLIP_ID, MEDICINE_ID) REFERENCES SLIP_ITEM (SLIP_ID, MEDICINE_ID)
);

-- 10) 알림 (MISMATCH: 수량 불일치 / LOW_STOCK: 재고 부족)
-- OUTBOUND_ID는 LOW_STOCK일 때 연결할 반출 건이 없어서 NULL 허용
CREATE TABLE ALERT (
    ALERT_ID        NUMBER(10)    NOT NULL,
    MEDICINE_ID     NUMBER(19)    NOT NULL,
    OUTBOUND_ID     NUMBER(10),
    ALERT_TYPE      VARCHAR2(20)  NOT NULL,
    ALERT_CONTENT   VARCHAR2(500) NOT NULL,
    PROCESS_STATUS  VARCHAR2(20)  DEFAULT 'PENDING' NOT NULL,
    ALERT_TIME      DATE          NOT NULL,
    CONSTRAINT PK_ALERT PRIMARY KEY (ALERT_ID),
    CONSTRAINT CK_ALERT_TYPE CHECK (ALERT_TYPE IN ('MISMATCH', 'LOW_STOCK')),
    CONSTRAINT CK_ALERT_STATUS CHECK (PROCESS_STATUS IN ('PENDING', 'DONE')),
    CONSTRAINT FK_ALERT_MEDICINE FOREIGN KEY (MEDICINE_ID) REFERENCES MEDICINE (MEDICINE_ID),
    CONSTRAINT FK_ALERT_OUTBOUND FOREIGN KEY (OUTBOUND_ID) REFERENCES OUTBOUND (OUTBOUND_ID)
);
