-- SLIP(전표 헤더) / SLIP_ITEM(전표 품목) 분리
-- 실행 전 SLIP, OUTBOUND, ALERT 데이터가 0건인 것을 확인함 (마이그레이션 불필요)

-- 1) SLIP: 품목 정보(수량, 의약품명)를 헤더에서 제거
ALTER TABLE SLIP DROP COLUMN REQUEST_QTY;
ALTER TABLE SLIP DROP COLUMN SLIP_MEDICINE;

-- 2) SLIP_ITEM: 전표 1개에 여러 품목(No.1, 2, 3...)
--    같은 전표에 같은 약이 두 줄 들어가지 못하도록 (SLIP_ID, MEDICINE_ID)를 UNIQUE로 둔다.
--    OUTBOUND가 이 UNIQUE 키를 복합 FK로 참조한다.
CREATE TABLE SLIP_ITEM (
    SLIP_ID      VARCHAR2(100) NOT NULL,
    ITEM_NO      NUMBER(3)     NOT NULL,
    MEDICINE_ID  NUMBER(19)    NOT NULL,
    REQUEST_QTY  NUMBER(10)    NOT NULL,
    CONSTRAINT PK_SLIP_ITEM PRIMARY KEY (SLIP_ID, ITEM_NO),
    CONSTRAINT UK_SLIP_ITEM_MEDICINE UNIQUE (SLIP_ID, MEDICINE_ID),
    CONSTRAINT FK_SLIP_ITEM_SLIP FOREIGN KEY (SLIP_ID) REFERENCES SLIP (SLIP_ID),
    CONSTRAINT FK_SLIP_ITEM_MEDICINE FOREIGN KEY (MEDICINE_ID) REFERENCES MEDICINE (MEDICINE_ID)
);

-- 3) OUTBOUND: "이 전표에 적힌 약만 출고 기록에 넣을 수 있다"를 DB가 보장하도록 복합 FK 추가
--    (기존 OUTBOUND의 SLIP_ID / MEDICINE_ID / WARD_ID 컬럼과 개별 FK는 그대로 유지)
ALTER TABLE OUTBOUND ADD CONSTRAINT FK_OUTBOUND_SLIP_ITEM
    FOREIGN KEY (SLIP_ID, MEDICINE_ID) REFERENCES SLIP_ITEM (SLIP_ID, MEDICINE_ID);
