-- WARD 대체키(surrogate key) 도입
-- 문제: WARD_ID(문자열, 예: '7병동')가 PK라서 전역으로 유일해야 함 -> 병원(admin)이 다른데
-- 같은 병동번호를 쓰면 충돌함. WARD_ID를 "코드(WARD_CODE)"로 내리고, 진짜 PK는
-- 새 대체키(WARD_SEQ_ID)로 바꿔서 (ADMIN_ID, WARD_CODE)만 유일하면 되게 한다.
--
-- 실행 전 확인 (2026-09-21):
--   WARD 4건 / SLIP 12건 / OUTBOUND 18건
--   WARD PK = SYS_C0030938 (WARD_ID) / 이 PK를 참조하는 FK는 SLIP.SYS_C0030943, OUTBOUND.SYS_C0030959 두 개뿐
--   (다른 테이블은 WARD를 참조하지 않음)

-- 1) WARD: WARD_ID -> WARD_CODE로 이름만 변경 (PK 제약은 잠시 그대로 유지)
ALTER TABLE WARD RENAME COLUMN WARD_ID TO WARD_CODE;

-- 2) WARD: 새 대체키 컬럼 추가 후 기존 4건에 번호 채움 (이 프로젝트는 IDENTITY/SEQUENCE 대신
--    findMaxId()+1 방식을 쓰므로, 마이그레이션도 같은 방식으로 1부터 순서대로 채운다)
ALTER TABLE WARD ADD (WARD_SEQ_ID NUMBER(10));

UPDATE WARD SET WARD_SEQ_ID = ROWNUM;

COMMIT;

ALTER TABLE WARD MODIFY (WARD_SEQ_ID NOT NULL);

-- 3) SLIP / OUTBOUND: 새 대체키를 담을 컬럼 추가 후, 기존 WARD_CODE 값으로 조인해서 채움
ALTER TABLE SLIP ADD (WARD_SEQ_ID NUMBER(10));

UPDATE SLIP s
   SET s.WARD_SEQ_ID = (SELECT w.WARD_SEQ_ID FROM WARD w WHERE w.WARD_CODE = s.WARD_ID);

ALTER TABLE OUTBOUND ADD (WARD_SEQ_ID NUMBER(10));

UPDATE OUTBOUND o
   SET o.WARD_SEQ_ID = (SELECT w.WARD_SEQ_ID FROM WARD w WHERE w.WARD_CODE = o.WARD_ID);

COMMIT;

ALTER TABLE SLIP MODIFY (WARD_SEQ_ID NOT NULL);
ALTER TABLE OUTBOUND MODIFY (WARD_SEQ_ID NOT NULL);

-- 4) 옛 FK/PK 제거 (숫자 대체키로 옮겨가기 전 마지막 정리)
ALTER TABLE SLIP DROP CONSTRAINT SYS_C0030943;
ALTER TABLE OUTBOUND DROP CONSTRAINT SYS_C0030959;
ALTER TABLE WARD DROP CONSTRAINT SYS_C0030938;

-- 5) 옛 문자열 WARD_ID 컬럼 제거, 새 대체키 컬럼을 WARD_ID로 이름 변경 (SLIP/OUTBOUND 쪽)
ALTER TABLE SLIP DROP COLUMN WARD_ID;
ALTER TABLE SLIP RENAME COLUMN WARD_SEQ_ID TO WARD_ID;

ALTER TABLE OUTBOUND DROP COLUMN WARD_ID;
ALTER TABLE OUTBOUND RENAME COLUMN WARD_SEQ_ID TO WARD_ID;

-- 6) WARD: 새 PK + 병원별 병동번호 유일성 제약
ALTER TABLE WARD ADD CONSTRAINT PK_WARD PRIMARY KEY (WARD_SEQ_ID);
ALTER TABLE WARD ADD CONSTRAINT UK_WARD_ADMIN_CODE UNIQUE (ADMIN_ID, WARD_CODE);

-- 7) SLIP / OUTBOUND: 새 숫자 PK를 참조하는 FK 재생성
ALTER TABLE SLIP ADD CONSTRAINT FK_SLIP_WARD FOREIGN KEY (WARD_ID) REFERENCES WARD (WARD_SEQ_ID);
ALTER TABLE OUTBOUND ADD CONSTRAINT FK_OUTBOUND_WARD FOREIGN KEY (WARD_ID) REFERENCES WARD (WARD_SEQ_ID);
